### ISSUE TITLE
Make full non-minified JS available for forking

### ISSUE THREAD

**Issue by sjz2018** [sim51/neosig#2]
Hi,

I wanted to make improvements to your neosig JS application but I cannot modify a minified JS document. 

If you aren't working on this actively, are you able to upload the non-minifed JS source code so that I can fork and modify it?

Thank you

**Comment by sim51** [comment]
Hi,

Sorry for the lag of my response.
All the source code are in this repository under the `src` folder.
The `doc` folder contains the minified JS that is build with webpack.

Cheers
