### ISSUE TITLE
update to sigma.js v2?

### ISSUE THREAD

**Issue by zlatent** [sim51/neosig#25]
sigma.js released v2 with webgl support, which can handle much larger graphs. it'd be really nice to update this to sigma.js v2. thanks!

**Comment by sim51** [comment]
Thanks for your feedback.

About sigmav2, I already know ^^

Now that Sigma v2 is based on graphology, I think that this repo will be archived.
In fact I already created a plugin for graphology :  https://github.com/sim51/graphology-neo4j

What is missing is the style of the graph, but it's not complexe todo. 
Perhaps giving just an example should be enought, I will see .

Also, Sigma 2 has not curved edges.
