### ISSUE TITLE
Can't resolve neosig

### ISSUE THREAD

**Issue by mafiqqq** [sim51/neosig#3]
Hi, I'm trying to add Neosig in my react application. I've used npm to install neosig 
`npm install neosig --save`
However, I keep getting neosig can't be resolved error.

Regarding the script tag, I used `react-helmet` to add the script, then I couldn't use `sigma` or `Neo4jGraph` 

thank you in advance for your help.

**Comment by sim51** [comment]
Can you show me a piece of code, on how you have integrated it ?

**Comment by mafiqqq** [comment]
Hey, I found another solution using https://github.com/dunnock/react-sigma 
I'll close this issue. Anyway thank you for replying ! 

Have a great day! 👍
